/*
 * Accounts Read Data Plane
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.quantumswap.app.api.read.model;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets TransactionType
 */
@JsonAdapter(TransactionType.Adapter.class)
public enum TransactionType {
  
  COINTRANSFER("CoinTransfer"),
  
  NEWTOKEN("NewToken"),
  
  TOKENTRANSFER("TokenTransfer"),
  
  NEWSMARTCONTRACT("NewSmartContract"),
  
  SMARTCONTRACT("SmartContract");

  private String value;

  TransactionType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static TransactionType fromValue(String text) {
    if (text == null) {
      return null;
    }
    for (TransactionType b : TransactionType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    // Unknown value from the server: return null rather than throwing so a single
    // row cannot abort deserialization of the whole transaction list (e.g. a
    // newly-added backend enum variant). The UI only uses this field for
    // labeling, so an unknown type simply renders as a generic transaction.
    return null;
  }

  public static class Adapter extends TypeAdapter<TransactionType> {
    @Override
    public void write(final JsonWriter jsonWriter, final TransactionType enumeration) throws IOException {
      if (enumeration == null) {
        jsonWriter.nullValue();
      } else {
        jsonWriter.value(enumeration.getValue());
      }
    }

    @Override
    public TransactionType read(final JsonReader jsonReader) throws IOException {
      if (jsonReader.peek() == com.google.gson.stream.JsonToken.NULL) {
        jsonReader.nextNull();
        return null;
      }
      String value = jsonReader.nextString();
      return TransactionType.fromValue(value);
    }
  }
}

